import type { Metadata } from "next";
import "./globals.css";
import "./theme-config.css";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import { Container, Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AuthProvider>
          <Theme
            appearance="light"
            accentColor="cyan"
            grayColor="sage"
            radius="large"
            scaling="95%"
            className="flex flex-row"
          >
            <NavBar />
            <main className="p-10 rounded-xl w-full">{children}</main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
